#!/usr/bin/env python3
from peewee import *
from playhouse.sqlite_ext import SqliteExtDatabase
from models.Cours import _create_tables
from models.Trombi import *
_create_tables()
pp=Eleve.create(nom="Dette", prenom="Thomas", date_naissance="12/02/2012", is_formateur=False, date_entree="12/03/1990")
#pp=Eleve.create(nom="Dette", prenom="Thomas", date_naissance="12/02/2012", telephone="06.22.33.14.55", courriel="thomas@patate.com", is_formateur=False, date_entree="12/03/1990", photo_path="./pics/portrait1.jpg")
pp.save()
pp=Eleve.create(nom="Ohjo", prenom="Oji", date_naissance="12/09/2000", telephone="06.12.23.34.45", courriel="dfff@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait2.jpg")
pp.save()
pp=Eleve.create(nom="Simpsons", prenom="Orde", date_naissance="12/09/2001", telephone="06.12.23.34.43", courriel="fzoef@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait3.jpg")
pp.save()
pp=Eleve.create(nom="Maison", prenom="Carré", date_naissance="12/10/2001", telephone="06.12.23.34.40", courriel="fronon@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait4.jpg")
pp.save()
pp=Eleve.create(nom="Azet", prenom="Iset", date_naissance="12/9/2000", telephone="06.12.23.34.37", courriel="iseese@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait5.jpg")
pp.save()
pp=Eleve.create(nom="Oze", prenom="Uzu", date_naissance="12/9/1998", telephone="06.12.23.34.32", courriel="fritz@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait6.jpg")
pp.save()
pp=Eleve.create(nom="Dfgui", prenom="Ou", date_naissance="12/9/1999", telephone="06.12.23.34.29", courriel="ffdoeizu@sqdfze.com", is_formateur=False, date_entree="12/12/2012", photo_path="./pics/portrait7.jpg")
pp.save()
