#!/usr/bin/env python3

from models.Cours import *
from models.dbDefs import FieldType

database.drop_table(Test)
database.create_table(Test)

def ajout_test(nom, nom_mf, description, mode):
    print('Ajout', nom, 'dans le module', nom_mf, ' : ', end='')
    try:
        mf=ModuleFormation.get(ModuleFormation.nom==nom_mf)
        test=Test(nom=nom, module=mf, description=description, mode=mode)
        test.save()
        print('done')
    except Exception as e:
        print('impossible (', e, ')')

ajout_test('Apnée 1', '100m', 'Faire une apnée', FieldType.E_BoolField.value)
ajout_test('Apnée 2', '100m', 'Faire une apnée', FieldType.E_BoolField.value)
ajout_test('Temps 100m', '100m', 'Faire 100m', FieldType.E_CharField.value)

ajout_test('Temps 200m', '250m', 'Nager', FieldType.E_CharField.value)
ajout_test('Temps 250m', '250m', 'Nager', FieldType.E_CharField.value)
