#!/usr/bin/env python3

from models.Cours import *

def ajout_mf(nom, nom_cours, categorie, description):
    try:
        cc=Cours.get(Cours.nom==nom_cours)
        mf=ModuleFormation(nom=nom, cours=cc, categorie=categorie, description=description)
        mf.save()
    except:
        print('Ajout', nom, 'dans', nom_cours, 'impossible')

ajout_mf('100m', 'Piscine', 'à voir', 'Faire 100m et sortir de l\'eau')
ajout_mf('200m', 'Piscine', 'à voir', 'Faire 200m et sortir de l\'eau')
